---
- name: Install zookeeper packages
  apt: name={{item}} state=installed
  with_items:
    - zookeeperd
    - zookeeper
    - zookeeper-bin

- name: Configure node ID
  copy: content={{zoo_id}} dest=/etc/zookeeper/conf/myid mode=644
  notify: Restart zookeeper

- name: Configure zookeeper servers
  template: src=etc-zookeeper-conf-zoo.cfg dest=/etc/zookeeper/conf/zoo.cfg mode=0644

- name: Start zookeeper
  service: name=zookeeper state=started enabled=yes
