## Docker Engine Authentication
#
# As explained in the [Marathon
# docs](https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html)
# using private registries requires that credentials are provided using an
# archive. This archive is generated during cluster provisioning on all Mesos
# agents based on credentials in `credentials/secret.yml`.
#
# Requires the credentials for all Docker registries to log into to be defined via
# the `docker_credentials` configuration variable.
#
# Note: this will run `docker login` on all hosts.
---
- name: Check if /etc/docker.tar.gz exists
  stat: path=/etc/docker.tar.gz
  register: docker_tar_gz

- name: Authenticate to Docker registries
  command: docker login -e {{item.email}} -u {{item.username}} -p {{item.password}} {{item.server}}
  when: docker_tar_gz.stat.exists == false
  with_items: docker_credentials

- name: Generate Docker auth archive
  shell: cd ~ && tar czf /etc/docker.tar.gz .docker/config.json
  when: docker_tar_gz.stat.exists == false
