---
# Note: this will run `docker login` on all hosts.
- name: Check if /etc/docker.tar.gz exists
  stat: path=/etc/docker.tar.gz
  register: docker_tar_gz

- name: Authenticate to Docker registries
  command: docker login -e {{item.email}} -u {{item.username}} -p {{item.password}} {{item.server}}
  when: docker_tar_gz.stat.exists == false
  with_items: docker_credentials

- name: Generate Docker auth archive
  shell: cd ~ && tar czf /etc/docker.tar.gz .docker/config.json
