---
# Version to install.
marathon_lb_version: 1.1.1

# URL for downloading the version.
marathon_lb_url: "https://github.com/mesosphere/marathon-lb/archive/v{{marathon_lb_version}}.zip"

# Location of the downloaded package.
marathon_lb_zip: "/opt/marathon-lb-{{marathon_lb_version}}.zip"

# Directory where Marathon LB files are installed.
marathon_lb_dir: "/opt/marathon-lb-{{marathon_lb_version}}"

# Path to the PEM.
marathon_lb_pem: ''
