---
- name: Restart master services
  service: name={{item}} state=restarted
  with_items:
    - marathon
    - chronos
    - mesos-master

- name: Restart Chronos service
  service: name=chronos state=restarted
