---
- name: Restart master services
  service: name={{item}} state=restarted
  with_items:
    - marathon
    - chronos
    - mesos-master
    - mesos-dns
  notify: update-dns

- name: update-dns
  command: resolvconf -u
  when: ansible_os_family == "Debian"
