## Mesos DNS
#
# Install the Mesos DNS Go binary and configure it as a system service.
#
# Nodes are configured to use Mesos DNS by the [mesos](mesos.md) role.
---
- name: Download release
  get_url: url={{mesos_dns_url}} dest={{mesos_dns_bin}} mode=6440

- name: Make executable
  file: path={{mesos_dns_bin}} mode=755

- name: Configure Mesos DNS
  template: src={{item.template}} dest={{item.file}} mode=0644
  with_items:
    - { file: '/etc/mesos-dns.json', template: etc-mesos-dns.json.j2 }
    - { file: '/etc/init/mesos-dns.conf', template: etc-init-mesos-dns.conf.j2 }
  notify: Restart Mesos DNS service

- name: Start Mesos DNS service
  service: name=mesos-dns state=started enabled=yes
