# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :name => 'mesos-node-0', :ip => '10.141.141.10', :mem => 1024, :cpus => 1 },
  { :name => 'mesos-node-1', :ip => '10.141.141.11', :mem => 4096, :cpus => 1 },
  { :name => 'mesos-node-2', :ip => '10.141.141.12', :mem => 1024, :cpus => 1 }
]

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.ssh.insert_key = false

  nodes.each do |node|
    config.vm.define node[:name] do |instance|
      instance.vm.provider "virtualbox" do |vb|
        vb.customize ['modifyvm', :id, '--memory', node[:mem]]
        vb.customize ['modifyvm', :id, '--cpus', node[:cpus]]
        vb.customize ['modifyvm', :id, '--hwvirtex', 'on']
      end

      instance.vm.host_name = node[:name]
      instance.vm.network 'private_network', ip: node[:ip]

      instance.vm.provision :ansible do |ansible|
        ansible.playbook = 'site.yml'
        ansible.inventory_path = 'hosts'
        ansible.limit = node[:ip]
      end
    end
  end
end
