# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :name => 'mesos-node-0', :ip => '10.141.141.10', :mem => 1024, :cpus => 1, :box => 'ubuntu/trusty64' },
  { :name => 'mesos-node-1', :ip => '10.141.141.11', :mem => 4096, :cpus => 1, :box => 'ubuntu/trusty64' },
  { :name => 'mesos-node-2', :ip => '10.141.141.12', :mem => 1536, :cpus => 1, :box => 'centos65-x86_64-20140116',
    :box_url => 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box'
  }
]

Vagrant.configure('2') do |config|
  config.ssh.insert_key = false

  nodes.each do |node|
    config.vm.define node[:name] do |instance|
      instance.vm.box = node[:box]
      instance.vm.box_url = node[:box_url] unless node[:box_url].nil?

      instance.vm.provider "virtualbox" do |vb|
        vb.customize ['modifyvm', :id, '--memory', node[:mem]]
        vb.customize ['modifyvm', :id, '--cpus', node[:cpus]]
        vb.customize ['modifyvm', :id, '--hwvirtex', 'on']
      end

      instance.vm.host_name = node[:name]
      instance.vm.network 'private_network', ip: node[:ip]
      if node[:name] == "mesos-node-2"
        instance.vm.provision :ansible do |ansible|
        ansible.playbook = 'site.yml'
        ansible.inventory_path = 'hosts'
        ansible.limit = "all"
        end
      end
    end
  end
end
