## Marathon Load Balancer
#
# Install and configure HAProxy and marathon-lb as system services. Once
# installed it will automatically map external domains to internal Marathon
# services using application descriptor labels.
---
# FIXME: Switch to docker image?
#
#  $ docker run --net host \
#      -e HAPROXY_SSL_CERT="$(cat /etc/ssl/mesosphere.com.pem)" \
#      mesosphere/marathon-lb sse \
#      -m http://leader.mesos:8080
# Based on http://programmableinfrastructure.com/guides/service-discovery/mesos-dns-haproxy-marathon/
- name: Add HAProxy PPA APT repo
  apt_repository: repo="ppa:vbernat/haproxy-1.6"

- name: Install HAProxy
  apt: name=haproxy

- name: Download marathon-lb
  get_url: url={{marathon_lb_url}} dest={{marathon_lb_zip}}

- name: Extract binary
  unarchive: src={{marathon_lb_zip}} dest=/opt copy=no creates={{marathon_lb_dir}}

- name: Change lua getpids script path
  replace: dest="{{ marathon_lb_dir }}/marathon_lb.py" regexp='.*lua-load /marathon-lb/getpids.lua' replace="      lua-load {{ marathon_lb_dir }}/getpids.lua"

- name: Change lua getconfig script path
  replace: dest="{{ marathon_lb_dir }}/marathon_lb.py" regexp='.*lua-load /marathon-lb/getconfig.lua' replace="      lua-load {{ marathon_lb_dir }}/getconfig.lua"

- name: Comment healthcheck
  replace: dest="{{ marathon_lb_dir }}/marathon_lb.py" regexp='^  option  httpchk GET {healthCheckPath}' replace="#  option  httpchk GET {healthCheckPath}"

- name: Configure marathon-lb
  template: src=etc-init-marathon-lb.conf.j2 dest=/etc/init/marathon-lb.conf mode=0644
  notify: Restart Marathon LB service

- name: Install SSL PEM
  copy: src={{marathon_lb_pem}} dest="/etc/ssl/mesosphere.com.pem" mode=0600
  when: marathon_lb_pem != ''

- name: Install PIP
  apt: name=python-pip state=installed

- name: Install PIP dependencies
  pip: requirements="{{ marathon_lb_dir }}/requirements.txt"

- name: Start service
  service: name=marathon-lb state=started enabled=yes
