---
- name: remove old kernels
  apt: name={{item}} state=absent autoremove=yes purge=yes
  with_items:
    - linux-image-3.13.0-32-generic
    - linux-image-extra-3.13.0-32-generic
    - linux-image-3.13.0-93-generic
    - linux-image-extra-3.13.0-93-generic
    - linux-image-3.16.0-62-generic
    - linux-image-extra-3.16.0-62-generic
    - linux-image-3.19.0-56-generic
    - linux-image-extra-3.19.0-56-generic
    - linux-image-3.19.0-58-generic
    - linux-image-extra-3.19.0-58-generic
    - linux-image-3.19.0-59-generic
    - linux-image-extra-3.19.0-59-generic
    - linux-image-3.19.0-64-generic
    - linux-image-extra-3.19.0-64-generic
    - linux-image-3.19.0-65-generic
    - linux-image-extra-3.19.0-65-generic
    - linux-image-3.19.0-66-generic
    - linux-image-extra-3.19.0-66-generic
    - linux-image-3.19.0-79-generic
    - linux-image-extra-3.19.0-79-generic
    - linux-image-4.4.0-34-generic
    - linux-image-extra-4.4.0-34-generic
    - linux-image-4.4.0-51-generic
    - linux-image-extra-4.4.0-51-generic
    - linux-image-4.4.0-53-generic
    - linux-image-extra-4.4.0-53-generic
    - linux-image-4.4.0-57-generic
    - linux-image-extra-4.4.0-57-generic
    - linux-image-4.4.0-59-generic
    - linux-image-extra-4.4.0-59-generic
    - linux-image-4.4.0-62-generic
    - linux-image-extra-4.4.0-62-generic
    - linux-image-4.4.0-63-generic
    - linux-image-extra-4.4.0-63-generic
    - linux-image-4.4.0-64-generic
    - linux-image-extra-4.4.0-64-generic
    - linux-image-4.4.0-66-generic
    - linux-image-extra-4.4.0-66-generic
    - linux-image-4.4.0-70-generic
    - linux-image-extra-4.4.0-70-generic
    - linux-image-4.4.0-71-generic
    - linux-image-extra-4.4.0-71-generic
    - linux-image-4.4.0-72-generic
    - linux-image-extra-4.4.0-72-generic
    - linux-image-4.4.0-73-generic
    - linux-image-extra-4.4.0-73-generic
    - linux-image-4.4.0-75-generic
    - linux-image-extra-4.4.0-75-generic
    - linux-image-4.4.0-77-generic
    - linux-image-extra-4.4.0-77-generic
    - linux-image-4.4.0-78-generic
    - linux-image-extra-4.4.0-78-generic
    - linux-image-4.4.0-79-generic
    - linux-image-extra-4.4.0-79-generic
    - linux-image-4.4.0-81-generic
    - linux-image-extra-4.4.0-81-generic
    - linux-image-4.4.0-83-generic
    - linux-image-extra-4.4.0-83-generic
    - linux-image-4.4.0-87-generic
    - linux-image-extra-4.4.0-87-generic
    - linux-image-4.4.0-89-generic
    - linux-image-extra-4.4.0-89-generic

- name: Install kernel
  apt: name=linux-image-generic state=latest
  register: newkernel

- name: remove cloud grub configs (vagrant images)
  file: path=/etc/default/grub.d/50-cloudimg-settings.cfg state=absent

- name: set grub kernel boot option for mesos-slave swap limit
  lineinfile: dest=/etc/default/grub regexp="^GRUB_CMDLINE_LINUX_DEFAULT=" line='GRUB_CMDLINE_LINUX_DEFAULT="swapaccount=1 console=tty0 console=tty1"' state=present
  notify: update_grub

- meta: flush_handlers

#- shell:  sleep 2 && reboot
#  when: newkernel.changed
#  async: 1
#  poll: 0
#  ignore_errors: true

#- name: waiting for server to come back
#  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=120 port=22
#  when: newkernel.changed
#  sudo: False
