---
- name: Install kernel
  apt: name=linux-image-generic state=latest
  register: newkernel

- name: remove cloud grub configs (vagrant images)
  file: path=/etc/default/grub.d/50-cloudimg-settings.cfg state=absent

- name: set grub kernel boot option for mesos-slave swap limit
  lineinfile: dest=/etc/default/grub regexp="^GRUB_CMDLINE_LINUX_DEFAULT=" line='GRUB_CMDLINE_LINUX_DEFAULT="swapaccount=1 console=tty0 console=tty1"' state=present
  notify: update_grub

- meta: flush_handlers

#- shell:  sleep 2 && reboot
#  when: newkernel.changed
#  async: 1
#  poll: 0
#  ignore_errors: true

#- name: waiting for server to come back
#  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=120 port=22
#  when: newkernel.changed
#  sudo: False
