---
- name: Update kernel
  yum: name=kernel-debug state=latest
  register: newkernel.changed

#- shell:  sleep 2 && reboot
#  when: newkernel.changed
#  async: 1
#  poll: 0
#  ignore_errors: true

#- name: waiting for server to come back
#  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=120 port=22
#  when: newkernel.changed
#  sudo: False
