## DCOS Command Line Interface
#
# Install DCOS CLI and configure for use "inside the cluster" with configured
# master nodes. The configuration relies on Mesos DNS to provide the Mesos master
# and Marathon endpoints.
---
- name: Install PIP
  apt: name=python-pip state=latest
  sudo: True

- name: Install DCOS CLI
  pip: name=dcoscli state=present version=0.2.0
  sudo: True

- name: Create DCOS CLI config directory
  file: path=~/.dcos state=directory mode=0700

- name: Configure DCOS CLI
  template: src=dcos.toml.j2 dest=~/.dcos/dcos.toml mode=0600
