---
- name: Set kafka facts
  set_fact:
    kafka_api_port: "41235"

- name: Install PIP
  apt: name=python-pip state=installed

- name: Install DCOS CLI
  pip: name={{item}} state=latest
  with_items:
    - dcoscli
    - six
    - requests

- name: Create DCOS CLI config directory
  file: path=~/.dcos state=directory mode=0700
  become_user: "{{ansible_ssh_user}}"

- name: Configure DCOS CLI
  template: src=dcos.toml.j2 dest=~/.dcos/dcos.toml mode=0600
  become_user: "{{ansible_ssh_user}}"
