## DCOS Command Line Interface
#
# Install DCOS CLI and configure for use "inside the cluster" with configured
# master nodes. The configuration relies on Mesos DNS to provide the Mesos master
# and Marathon endpoints.
---
- name: Install PIP
  apt: name=python-pip state=latest

- name: Install DCOS CLI
  pip: name={{item}} state=latest
  with_items:
    - dcoscli
    - six
    - requests

- name: Create DCOS CLI config directory
  file: path=~/.dcos state=directory mode=0700
  become_user: "{{ansible_ssh_user}}"

- name: Configure DCOS CLI
  template: src=dcos.toml.j2 dest=~/.dcos/dcos.toml mode=0600
  become_user: "{{ansible_ssh_user}}"
