---
- name: Add Mesosphere APT key
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF state=present
  ignore_errors: true

- name: Add Mesosphere APT repo
  apt_repository: repo="deb http://repos.mesosphere.io/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main" state=present

- name: Install Mesos package
  apt: name={{item}} state=installed force=yes
  with_items:
    - mesos={{mesos_version}}*

# The Mesos Debian package depends on Zookeeper, which we install in a separate
# role. Since master nodes and agent nodes in particular can be configured to
# not run Zookeeeper we disable the service explicitly.
- name: Disable Zookeeper for non-zookeeper hosts
  service: name=zookeeper state=stopped enabled=no
  when: "'zookeeper' not in group_names"

# The Mesos package installs both the master and agent. Make the Mesos services
# match those of the roles.
- name: Disable Mesos Master for non-master hosts
  service: name=mesos-master state=stopped enabled=no
  when: "'mesos-master' not in group_names"

- name: Disable Mesos Agent for non-agent hosts
  service: name=mesos-slave state=stopped enabled=no
  when: "'mesos-agent' not in group_names"

