---
- name: Set Mesos cluster facts
  set_fact:
    mesos_quorom: "{{ (groups['mesos-master'] | count / 2) | round(0, 'ceil') | int }}"
    mesos_zk_url: "zk://{{ groups.zookeeper | join(':2181,') }}:2181/mesos"
    mesos_credentials_principal: "{{ mesos_credentials.principal }}"
    mesos_credentials_secret: "{{ mesos_credentials.secret }}"
    mesos_http_credentials: "{{ mesos_http_credentials }}"
    mesos_master_url: "http://{{ mesos_http_credentials }}@master.mesos:5050"
    marathon_url: "http://{{ mesos_http_credentials }}@marathon.mesos:8080"

- name: Add Mesosphere APT key
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF state=present

- name: Add Mesosphere APT repo
  apt_repository: repo="deb http://repos.mesosphere.io/ubuntu/ trusty main" state=present

- name: Configure Mesos DNS
  lineinfile: dest=/etc/resolvconf/resolv.conf.d/head insertbefore="^nameserver.*" regexp=".*{{item}}$" line="nameserver {{item}}" state=present
  with_items: groups['mesos-dns']
  notify: Regenerate /etc/resolv.conf

- name: Install Mesos package
  apt: name={{item}} state=installed
  with_items:
    - mesos={{mesos_version}}*

- name: Disable Zookeeper
  service: name=zookeeper state=stopped enabled=no
  when: "'zookeeper' not in group_names"

# The Mesos package installs both the master and agent. Make the Mesos services
# match those of the roles.
- name: Disable Mesos Master for non-master hosts
  service: name=mesos-master state=stopped enabled=no
  when: "'mesos-master' not in group_names"

- name: Disable Mesos Agent for non-agent hosts
  service: name=mesos-slave state=stopped enabled=no
  when: "'mesos-agent' not in group_names"
