## Mesos
#
# Install the Mesos package from the Mesosphere package repository and configure
# each node to use the Mesos DNS nodes as name server. Finally, disables services
# automatically installed by the Mesos package and not used by the node based on
# its assigned roles.
---
- name: Set Mesos cluster facts
  set_fact:
    mesos_quorom: "{{ (groups['mesos-master'] | count / 2 + 0.5) | round(0, 'ceil') | int }}"
# already in "common":    mesos_zk_url: "zk://{{ groups.zookeeper | join(':2181,') }}:2181/mesos"
    mesos_credentials_principal: "{{ mesos_credentials.principal }}"
    mesos_credentials_secret: "{{ mesos_credentials.secret }}"
    mesos_http_credentials: "{{ mesos_http_credentials }}"
    mesos_master_url: "http://{{ mesos_http_credentials }}@master.mesos:5050"
    marathon_url: "http://{{ mesos_http_credentials }}@marathon.mesos:{{marathon_port}}"

- name: Conditionally install Debian packages
  include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Conditionally install RedHat packages
  include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Configure Mesos DNS
  lineinfile: dest={{mesos_dns_config_file[ansible_os_family]}} insertbefore="^nameserver.*" regexp=".*{{item}}$" line="nameserver {{item}}" state=present
  with_items: groups['mesos-dns']
  notify: Regenerate /etc/resolv.conf
