---
- name: Set Mesos cluster facts
  set_fact:
    mesos_quorom: "{{ (groups['mesos-master'] | count / 2 + 0.5) | round(0, 'ceil') | int }}"
# already in "common":    mesos_zk_url: "zk://{{ groups.zookeeper | join(':2181,') }}:2181/mesos"
    mesos_credentials_principal: "{{ mesos_credentials.principal }}"
    mesos_credentials_secret: "{{ mesos_credentials.secret }}"
    mesos_http_credentials: "{{ mesos_http_credentials }}"
    mesos_master_url: "http://{{ mesos_http_credentials }}@master.mesos:5050"
    marathon_url: "http://{{ mesos_http_credentials }}@marathon.mesos:8080"

- name: Conditionally install Debian packages
  include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Conditionally install RedHat packages
  include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Configure Mesos DNS
  lineinfile: dest={{mesos_dns_config_file[ansible_os_family]}} insertbefore="^nameserver.*" regexp=".*{{item}}$" line="nameserver {{item}}" state=present
  with_items: groups['mesos-dns']
  notify: Regenerate /etc/resolv.conf

# The Mesos package installs both the master and agent. Make the Mesos services
# match those of the roles.
- name: Disable Mesos Master for non-master hosts
  service: name=mesos-master state=stopped enabled=no
  when: "'mesos-master' not in group_names"

- name: Disable Mesos Agent for non-agent hosts
  service: name=mesos-slave state=stopped enabled=no
  when: "'mesos-agent' not in group_names"
