---
- name: Add mesosphere repo
  yum: name={{mesosphere_repo}} state=present

- name: Install Mesos package
  yum: name={{item}} state=installed
  with_items:
    - mesos-{{mesos_version}}

# The Mesos package installs both the master and agent. Make the Mesos services
# match those of the roles.

- name: Check Mesos Master running
  shell: sudo status mesos-master
  when: "'mesos-master' not in group_names"
  register: mesos_master

- name: Disable Mesos Master for non-master hosts
  shell: sudo stop mesos-master
  when: "'running' in mesos_master.stdout"

- name: Disable Mesos Agent for non-agent hosts
  shell: sudo stop mesos-slave
  when: "'mesos-agent' not in group_names"
  ignore_errors: yes

