---
- name: Set gluster fs facts
  set_fact:
    glusterfs_quorum:  "{{ (groups['glusterfs_nodes']) | count | int }}"
    glusterfs_members: "{{ (groups['glusterfs_nodes']) | join(',') }}"
    
- name: connect gluster peers
  command: gluster peer probe {{ item }}
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  with_items: groups['glusterfs_nodes'] 
  ignore_errors: yes
   
- name: create gluster volume
  gluster_volume: state=present name=gfsvol0 host={{inventory_hostname}} rebalance=no force=yes replicas={{ glusterfs_quorum }} brick=/gfs_data cluster={{glusterfs_members}}
  run_once: true
  register: create_vol

- name: start gluster volume
  gluster_volume: state=started name=gfsvol0
  
- name: mounting gluster volumes
  mount: name='/mnt' src='localhost:/gfsvol0' fstype='glusterfs' opts='defaults,_netdev' state=mounted
#  when: "'errno 107' not in create_vol.stdout"
  notify: 
  - Restart mesos services
