## Java
#
# Install the Java SDK.
---
- name: install Debian
  include: Debian.yml
  when: ansible_os_family == "Debian"

- name: install Redhat
  include: RedHat.yml
  when: ansible_os_family == "RedHat"
