---
- name: Conditionally install Debian packages
  include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Conditionally install RedHat packages
  include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Start docker
  service: name=docker state=started enabled=yes
