---
- name: repo install
  template: src=RedHat_docker.j2 dest=/etc/yum.repos.d/docker.repo mode=0644

- name: Install os packages
  yum: name=docker-engine state=installed
  
- name: Start docker
  service: name=docker state=started enabled=yes