---
- name: Update APT
  apt: update_cache=yes cache_valid_time=3600 autoremove=yes

- name: Install base packages
  apt: name={{item}} state=latest
  with_items:
    - curl
    - unzip
    - ca-certificates
    - software-properties-common
    - python-netaddr
