---
- name: Update APT
  apt: update_cache=yes cache_valid_time=3600

- name: Install base packages
  apt: name={{item}} state=latest
  with_items:
    - curl
    - unzip
    - ca-certificates
    - software-properties-common

- name: Install kernel 3.16
  apt: name=linux-image-generic-lts-utopic state=latest
  register: newkernel

- shell:  sleep 2 && reboot
  when: newkernel.changed
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=120 port=22
  when: newkernel.changed
  sudo: False
