---
- name: Update APT
  apt: update_cache=yes cache_valid_time=3600

- name: Install base packages
  apt: name={{item}} state=latest
  with_items:
    - curl
    - unzip
    - ca-certificates
    - software-properties-common

- name: Install kernel 3.19
  apt: name=linux-generic-lts-vivid state=latest
  register: newkernel

- name: set grub kernel boot option for mesos-slave swap limit
  lineinfile: dest=/etc/default/grub regexp="^GRUB_CMDLINE_LINUX_DEFAULT=" line='GRUB_CMDLINE_LINUX_DEFAULT="swapaccount=1 console=tty0 console=tty1"' state=present
  notify: update_grub

- shell:  sleep 2 && reboot
  when: newkernel.changed
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=120 port=22
  when: newkernel.changed
  sudo: False
