---
- name: Set facts
  set_fact:
    mesos_zk_url: "zk://{{ groups.zookeeper | join(':2181,') }}:2181/mesos"

- name: Conditionally install Debian packages
  include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Update /etc/hosts to list all cluster nodes
  template: src=etc-hosts.j2 dest=/etc/hosts mode=0644
