---
- name: Install base packages
  yum: name={{item}} state=installed
  with_items:
    - curl
    - unzip
    - ca-certificates

# ToDo: this requires ansible 2.1
#- name: Add CentOSPlus RPM repository
#  yumrepo:
#    name: centosplus.
#    baseurl: http://mirror.centos.org/centos/$releasever/centosplus/$basearch.
#    mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus..
#    gpgcheck: yes.
#    includepkgs: kernel-firmware-*

- name: check kernel version
  shell: uname -r| tr -d '.|-' |cut -c 1-7
  register: version

- name: uninstall firmware
  yum: name={{item}} state=removed
  with_items:
    - kernel-firmware
  when: "'{{version.stdout}}' != '2632573'"
  register: newkernel
  changed_when: true

- name: update kernel-firmware
  get_url: dest=/home/{{ansible_ssh_user}}/kernel-firmware.rpm  url=ftp://fr2.rpmfind.net/linux/centos/6.7/centosplus/x86_64/Packages/kernel-firmware-2.6.32-573.18.1.el6.centos.plus.noarch.rpm mode=0644
  when: newkernel.changed

- shell: rpm -if /home/{{ansible_ssh_user}}/kernel-firmware.rpm
  when: newkernel.changed

- name: Update kernel
  yum: name=kernel-debug state=latest
  when: newkernel.changed

- shell: grubby --set-default=/boot/vmlinuz-2.6.32-573.18.1.el6.x86_64.debug
  when: newkernel.changed

- shell:  sleep 2 && reboot
  when: newkernel.changed
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=120 port=22
  when: newkernel.changed
  sudo: False
