---
- name: Downloading and enable the EPEL repository definitions.
  yum: name={{ epel_repo }} state=present

- name: Yum update 
  shell: sudo yum update -y

- name: Install os packages
  yum: name={{item}} state=present
  with_items:
    - wget
    - curl
    - unzip
    - libselinux-python 
    - python-setuptools
