---
- name: Install base packages
  yum: name={{item}} state=installed
  with_items:
    - curl
    - unzip
    - ca-certificates

- name: check kernel version
  shell: uname -r| tr -d '.|-' |cut -c 1-7
  register: version

- name: uninstall firmware
  yum: name={{item}} state=removed
  with_items:
    - kernel-firmware
  when: "'{{version.stdout}}' != '2632573'"
  register: newkernel

- name: update kernel-firmware
  get_url: dest=/home/{{ansible_ssh_user}}/kernel-firmware.rpm  url=ftp://fr2.rpmfind.net/linux/centos/6.7/centosplus/x86_64/Packages/kernel-firmware-2.6.32-573.18.1.el6.centos.plus.noarch.rpm mode=0644
  sudo: false
  when: newkernel.changed

- shell: rpm -if /home/{{ansible_ssh_user}}/kernel-firmware.rpm
  sudo: true
  when: newkernel.changed

- name: Update kernel
  yum: name=kernel-debug state=latest
  sudo: true
  when: newkernel.changed

- shell: grubby --set-default=/boot/vmlinuz-2.6.32-573.18.1.el6.x86_64.debug
  sudo: true
  when: newkernel.changed

- shell:  sleep 2 && reboot
  when: newkernel.changed
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=120 port=22
  sudo: false
  when: newkernel.changed
