## Docker Registry
#
# Deploy a Docker registry in the cluster as a Marathon application.
---
- name: Docker auth directory
  file: path=/etc/docker/auth state=directory mode=0700

- name: Install PIP tooling
  apt: name={{item}}  state=installed
  with_items: [ python-pip, python-bcrypt ]

# python-passlib APT package does not support bcrypt so install latest
# PIP version
- name: Install passlib packages
  pip: name=passlib state=present

- name: Generate Docker htpasswd file
  htpasswd:
    path: /etc/docker/auth/htpasswd
    crypt_scheme: bcrypt
    username: "{{item.username}}"
    password: "{{item.password}}"
  with_items: "{{docker_registry.auth.htpasswd.credentials}}"

# - name: Install htpasswd
#   apt: name=apache2-utils state=installed
#
# - name: Check if /etc/docker/auth/htpasswd exists
#   stat: path=/etc/docker/auht/htpasswd
#   register: docker_registry_htpasswd
#
# - name: Create /etc/docker/auth/htpasswd
#   file: path=/etc/docker/auth/htpasswd state=touch
#   register: create_htpasswd
#
# - name: Debug
#   debug: msg="{{create_htpasswd}}"
#
# - name: Generate Docker htpasswd file
#   command: htpasswd -bB /etc/docker/auth/htpasswd {{item.username}} {{item.password}}
#   when: docker_registry_htpasswd.stat.exists == false
#   with_items: "{{docker_registry.auth.htpasswd.credentials}}"

- name: Generate Docker registry Marathon file
  template: src=marathon.json.j2 dest=~/docker-registry.marathon.json
  become_user: "{{ansible_ssh_user}}"

- name: Deploy Docker registry
  shell: dcos marathon app add ~/docker-registry.marathon.json
  become_user: "{{ansible_ssh_user}}"
