#!/bin/bash
#
# Generate documentation for an Ansible role.
#
# Usage: $0 <role-name>
set -eu -o pipefail
IFS=$'\n\t'

role="$1"
role_dir="roles/$role"

newline='
'
indent='   '

extract_docs() {
  local doc= doc_sep= doc_started=

  {
    cat "$role_dir/$1"
    echo
  } | while read line; do
    case "$line" in
      "#"*)
        case "$line" in "##"*)
          doc_started=1
        esac
        if [ -n "$doc_started" ]; then
          echo "${line#\#}"
        fi
        ;;

      ""|"---")
        doc_started=
        ;;
    esac
  done
}

extract_defaults() {
  local doc= setting= example=
  local doc_sep= setting_sep= example_sep=

  {
    cat "$role_dir/$1"
    echo
  } | while read line; do
    case "$line" in
      "---")
        # Skip
        ;;

      "#"*)
        doc="$doc$doc_sep${line#\#}"
        doc_sep="$newline$indent"
        ;;

      "")
        echo
        echo " - $setting:"
        echo ""
        echo "   $doc"
        echo
        echo "   *Default*:"
        echo "   \`\`\`yaml"
        echo "   {% raw %}$example{% endraw %}"
        echo "   \`\`\`"

        doc= setting= example=
        doc_sep= setting_sep= example_sep=
        doc_started=
        ;;

      [a-z]*)
        example="$example$example_sep$line"
        example_sep="$newline$indent"

        setting="$setting$setting_sep\`${line%%\:*}\`"
        setting_sep=', '
        ;;

      *)
        example="$example$example_sep$line"
        example_sep="$newline$indent"
        ;;
    esac
  done
}

echo "<!-- AUTOGENERATED BY $@ FROM FILES IN $role_dir - DO NOT EDIT -->"
extract_docs "tasks/main.yml"

if [ -e "$role_dir/defaults/main.yml" ]; then
  echo "## Configuration"
  echo
  echo "Defaults are set in \`defaults/main.yml\`."

  extract_defaults "defaults/main.yml"
fi
