#!/bin/bash
#
# Generate Ansible role table of contents.
#
# Usage: $0 <toc-template> <role-name>*
set -eu -o pipefail
IFS=$'\n\t'

toc="$1"; shift

echo "<!-- AUTOGENERATED by $0 - DO NOT EDIT -->"
sed -n '0,/.*Roles are automatically added here/p' < "$toc"
while [ $# -ne 0 ]; do
  role="$1"; shift
  title="$(head -1 "roles/$role/tasks/main.yml" | sed 's/^#\+\s*//')"
  echo "    - [$title](roles/$role.md)"
done
sed -n '/.*Roles are automatically added here/,$p' < "$toc"
