- name: Install Mesos master packages
  apt: name={{item}} state=installed
  with_items:
    - marathon={{marathon_version}}*
    - chronos={{chronos_version}}*

- name: Configure master
  copy: content={{item.content}} dest={{item.file}} mode=644
  with_items:
    - { file: '/etc/mesos/zk', content: "{{mesos_zk_url}}" }
    - { file: '/etc/mesos-master/cluster', content: "'{{cluster_name}}'" }
    - { file: '/etc/mesos-master/hostname', content: "{{mesos_hostname}}" }
    - { file: '/etc/mesos-master/quorum', content: "{{mesos_quorom}}" }
    - { file: '/etc/mesos-master/authenticate', content: "true" }
    - { file: '/etc/mesos-master/authenticate_slaves', content: "true" }
    - { file: '/etc/mesos-master/credentials', content: "/etc/mesos-master/.credentials" }
    - { file: "{{ mesos_authentication_secret_file }}", content: "{{ mesos_credentials_secret }}" }
  notify: Restart master services

- name: Configure Mesos authentication
  template: src=etc-mesos-master-credentials.j2 dest=/etc/mesos-master/.credentials mode=600
  notify: Restart master services

- name: Configure Marathon
  template: src=etc-init-marathon.conf.j2 dest=/etc/init/marathon.conf mode=0644
  notify: Restart master services

- name: Configure Chronos
  template: src=etc-init-chronos.conf.j2 dest=/etc/init/chronos.conf mode=0644
  notify: Restart master services

- name: Start master services
  service: name={{item}} state=started enabled=yes
  with_items:
    - marathon
    - chronos
    - mesos-master
