---
- name: Configure agent
  copy: content={{item.content}} dest={{item.file}}
  with_items:
    - { file: '/etc/mesos/zk', content: "{{mesos_zk_url}}" }
    - { file: '/etc/mesos-slave/hostname', content: "{{inventory_hostname}}" }
    - { file: '/etc/mesos-slave/containerizers', content: 'docker,mesos' }
    - { file: '/etc/mesos-slave/isolation', content: 'cgroups/cpu,cgroups/mem' }
    - { file: '/etc/mesos-slave/executor_registration_timeout', content: '5mins' }
    - { file: '/etc/mesos-slave/attributes', content: "{{agent_attributes}}" }
    - { file: '/etc/mesos-slave/resources', content: "{{agent_resources}}" }
    - { file: '/etc/mesos-slave/fetcher_cache_size', content: "2GB" }
    - { file: '/etc/mesos-slave/work_dir', content: "/mnt/mesos" }
    - { file: '/etc/mesos-slave/fetcher_cache_dir', content: "/tmp/mesos" }
    - { file: '/etc/mesos-slave/credential', content: "/etc/init/mesos-slave-passwd" }
  notify: Restart agent service

- name: Configure agent auth
  template: src=etc-init-mesos-slave-passwd.j2 dest=/etc/init/mesos-slave-passwd mode=0600
  notify: Restart agent service

- name: Reset agent history
  file: path={{item}} state=absent
  with_items:
    - /tmp/mesos/meta/slaves
    - /tmp/mesos/slaves
  when: reset_agent is defined
  notify: Restart agent service

- name: Start agent
  service: name=mesos-slave state=started enabled=yes
